<?xml version='1.0' encoding='UTF-8'?>
<wfs:FeatureCollection
 xmlns:georbis='http://www.vizexperts.com/'
 xmlns:wfs='http://www.opengis.net/wfs'
 xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
 xmlns:gml='http://www.opengis.net/gml'
 xmlns:xsd='http://www.w3.org/2001/XMLSchema'
 xmlns:ogc='http://www.opengis.net/ogc'
 xmlns:xlink='http://www.w3.org/1999/xlink'
 xmlns:ows='http://www.opengis.net/ows'
 xsi:schemaLocation='http://www.vizexperts.com/
    http://192.168.1.36:19090/WFS?service=WFS&amp;version=1.0.0&amp;request=DescribeFeatureType&amp;Typename=georbis:georbis:world_boundaries   http://www.opengis.net/wfs
   http://schemas.opengis.net/wfs/1.0.0/WFS-basic.xsd
   http://www.opengis.net/gml
   http://schemas.opengis.net/gml/2.1.2/feature.xsd'
>
<gml:boundedBy><gml:null>missing</gml:null></gml:boundedBy>
  <gml:featureMember>
   <georbis:world_boundaries fid="world_boundaries.14">
   <georbis:fips>BG</georbis:fips>
   <georbis:iso2>BD</georbis:iso2>
   <georbis:iso3>BGD</georbis:iso3>
   <georbis:un>50</georbis:un>
   <georbis:name>Bangladesh</georbis:name>
   <georbis:area>13017</georbis:area>
   <georbis:pop2005>15328112</georbis:pop2005>
   <georbis:region>142</georbis:region>
   <georbis:subregion>34</georbis:subregion>
   <georbis:lon>89.941</georbis:lon>
   <georbis:lat>24.218</georbis:lat>
   <georbis:geom>...</georbis:geom>
   </georbis:world_boundaries>
  </gml:featureMember>
  <gml:featureMember>
   <georbis:world_boundaries fid="world_boundaries.18">
   <georbis:fips>BM</georbis:fips>
   <georbis:iso2>MM</georbis:iso2>
   <georbis:iso3>MMR</georbis:iso3>
   <georbis:un>104</georbis:un>
   <georbis:name>Burma</georbis:name>
   <georbis:area>65755</georbis:area>
   <georbis:pop2005>47967266</georbis:pop2005>
   <georbis:region>142</georbis:region>
   <georbis:subregion>35</georbis:subregion>
   <georbis:lon>96.041</georbis:lon>
   <georbis:lat>21.718</georbis:lat>
   <georbis:geom>...</georbis:geom>
   </georbis:world_boundaries>
  </gml:featureMember>
  <gml:featureMember>
   <georbis:world_boundaries fid="world_boundaries.26">
   <georbis:fips>CE</georbis:fips>
   <georbis:iso2>LK</georbis:iso2>
   <georbis:iso3>LKA</georbis:iso3>
   <georbis:un>144</georbis:un>
   <georbis:name>Sri Lanka</georbis:name>
   <georbis:area>6463</georbis:area>
   <georbis:pop2005>19120763</georbis:pop2005>
   <georbis:region>142</georbis:region>
   <georbis:subregion>34</georbis:subregion>
   <georbis:lon>80.704</georbis:lon>
   <georbis:lat>7.612</georbis:lat>
   <georbis:geom>...</georbis:geom>
   </georbis:world_boundaries>
  </gml:featureMember>
  <gml:featureMember>
   <georbis:world_boundaries fid="world_boundaries.30">
   <georbis:fips>CH</georbis:fips>
   <georbis:iso2>CN</georbis:iso2>
   <georbis:iso3>CHN</georbis:iso3>
   <georbis:un>156</georbis:un>
   <georbis:name>China</georbis:name>
   <georbis:area>932743</georbis:area>
   <georbis:pop2005>1312978855</georbis:pop2005>
   <georbis:region>142</georbis:region>
   <georbis:subregion>30</georbis:subregion>
   <georbis:lon>106.514</georbis:lon>
   <georbis:lat>33.42</georbis:lat>
   <georbis:geom>...</georbis:geom>
   </georbis:world_boundaries>
  </gml:featureMember>
  <gml:featureMember>
   <georbis:world_boundaries fid="world_boundaries.31">
   <georbis:fips>AF</georbis:fips>
   <georbis:iso2>AF</georbis:iso2>
   <georbis:iso3>AFG</georbis:iso3>
   <georbis:un>4</georbis:un>
   <georbis:name>Afghanistan</georbis:name>
   <georbis:area>65209</georbis:area>
   <georbis:pop2005>25067407</georbis:pop2005>
   <georbis:region>142</georbis:region>
   <georbis:subregion>34</georbis:subregion>
   <georbis:lon>65.216</georbis:lon>
   <georbis:lat>33.677</georbis:lat>
   <georbis:geom>...</georbis:geom>
   </georbis:world_boundaries>
  </gml:featureMember>
  <gml:featureMember>
   <georbis:world_boundaries fid="world_boundaries.32">
   <georbis:fips>BT</georbis:fips>
   <georbis:iso2>BT</georbis:iso2>
   <georbis:iso3>BTN</georbis:iso3>
   <georbis:un>64</georbis:un>
   <georbis:name>Bhutan</georbis:name>
   <georbis:area>4700</georbis:area>
   <georbis:pop2005>637013</georbis:pop2005>
   <georbis:region>142</georbis:region>
   <georbis:subregion>34</georbis:subregion>
   <georbis:lon>90.429</georbis:lon>
   <georbis:lat>27.415</georbis:lat>
   <georbis:geom>...</georbis:geom>
   </georbis:world_boundaries>
  </gml:featureMember>
  <gml:featureMember>
   <georbis:world_boundaries fid="world_boundaries.83">
   <georbis:fips>IN</georbis:fips>
   <georbis:iso2>IN</georbis:iso2>
   <georbis:iso3>IND</georbis:iso3>
   <georbis:un>356</georbis:un>
   <georbis:name>India</georbis:name>
   <georbis:area>297319</georbis:area>
   <georbis:pop2005>1134403141</georbis:pop2005>
   <georbis:region>142</georbis:region>
   <georbis:subregion>34</georbis:subregion>
   <georbis:lon>78.5</georbis:lon>
   <georbis:lat>21</georbis:lat>
   <georbis:geom>...</georbis:geom>
   </georbis:world_boundaries>
  </gml:featureMember>
  <gml:featureMember>
   <georbis:world_boundaries fid="world_boundaries.156">
   <georbis:fips>NP</georbis:fips>
   <georbis:iso2>NP</georbis:iso2>
   <georbis:iso3>NPL</georbis:iso3>
   <georbis:un>524</georbis:un>
   <georbis:name>Nepal</georbis:name>
   <georbis:area>14300</georbis:area>
   <georbis:pop2005>27093656</georbis:pop2005>
   <georbis:region>142</georbis:region>
   <georbis:subregion>34</georbis:subregion>
   <georbis:lon>83.939</georbis:lon>
   <georbis:lat>28.253</georbis:lat>
   <georbis:geom>...</georbis:geom>
   </georbis:world_boundaries>
  </gml:featureMember>
  <gml:featureMember>
   <georbis:world_boundaries fid="world_boundaries.163">
   <georbis:fips>PK</georbis:fips>
   <georbis:iso2>PK</georbis:iso2>
   <georbis:iso3>PAK</georbis:iso3>
   <georbis:un>586</georbis:un>
   <georbis:name>Pakistan</georbis:name>
   <georbis:area>77088</georbis:area>
   <georbis:pop2005>158080591</georbis:pop2005>
   <georbis:region>142</georbis:region>
   <georbis:subregion>34</georbis:subregion>
   <georbis:lon>69.386</georbis:lon>
   <georbis:lat>29.967</georbis:lat>
   <georbis:geom>...</georbis:geom>
   </georbis:world_boundaries>
  </gml:featureMember>
  <gml:featureMember>
   <georbis:world_boundaries fid="world_boundaries.195">
   <georbis:fips>TH</georbis:fips>
   <georbis:iso2>TH</georbis:iso2>
   <georbis:iso3>THA</georbis:iso3>
   <georbis:un>764</georbis:un>
   <georbis:name>Thailand</georbis:name>
   <georbis:area>51089</georbis:area>
   <georbis:pop2005>63002911</georbis:pop2005>
   <georbis:region>142</georbis:region>
   <georbis:subregion>35</georbis:subregion>
   <georbis:lon>100.844</georbis:lon>
   <georbis:lat>15.7</georbis:lat>
   <georbis:geom>...</georbis:geom>
   </georbis:world_boundaries>
  </gml:featureMember>
  <gml:featureMember>
   <georbis:world_boundaries fid="world_boundaries.196">
   <georbis:fips>TI</georbis:fips>
   <georbis:iso2>TJ</georbis:iso2>
   <georbis:iso3>TJK</georbis:iso3>
   <georbis:un>762</georbis:un>
   <georbis:name>Tajikistan</georbis:name>
   <georbis:area>13996</georbis:area>
   <georbis:pop2005>6550213</georbis:pop2005>
   <georbis:region>142</georbis:region>
   <georbis:subregion>143</georbis:subregion>
   <georbis:lon>69.42</georbis:lon>
   <georbis:lat>38.665</georbis:lat>
   <georbis:geom>...</georbis:geom>
   </georbis:world_boundaries>
  </gml:featureMember>
  <gml:featureMember>
   <georbis:world_boundaries fid="world_boundaries.212">
   <georbis:fips>UZ</georbis:fips>
   <georbis:iso2>UZ</georbis:iso2>
   <georbis:iso3>UZB</georbis:iso3>
   <georbis:un>860</georbis:un>
   <georbis:name>Uzbekistan</georbis:name>
   <georbis:area>42540</georbis:area>
   <georbis:pop2005>26593123</georbis:pop2005>
   <georbis:region>142</georbis:region>
   <georbis:subregion>143</georbis:subregion>
   <georbis:lon>63.17</georbis:lon>
   <georbis:lat>41.75</georbis:lat>
   <georbis:geom>...</georbis:geom>
   </georbis:world_boundaries>
  </gml:featureMember>
</wfs:FeatureCollection>
